Change from raw.github.com to rawgithub.com
```
Refused to execute script from 'https://raw.github.com/gregstewart/orbital-dial/master/dist/orbital-dial.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. (index):1
Uncaught TypeError: object is not a function 
```